name: json_to_dart
description: A simple json to dart model generator

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  dart_style: ^2.2.4
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_highlight: ^0.7.0
  flutter_image_compress: ^1.1.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^7.0.1
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  highlight: ^0.7.0
  intl: ^0.17.0
  json_editor: ^0.0.8
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.8
  url_strategy: ^0.2.0

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - "asset/"
